import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pad_sequence
import pickle
from collections import Counter
import re

# Sample data (text descriptions and labels)
data = [
    ("The child was helping parents in a shop", 0),
    ("The child was selling tea at the railway station", 1),
    ("The child was working in a glass factory", 2),
    ("The child was playing in a park", 0),
    ("The child was picking garbage on the street", 1),
    ("The child was going to school regularly", 0),
    ("The child was working in a hazardous chemical plant", 2),
    ("The child was singing songs at a wedding", 1),
    ("The child was involved in mining activities", 2),
    ("The child was helping in household chores", 0),
    ("The child was helping parents in a shop", 0),
    ("The child was selling tea at the railway station", 1),
    ("The child was working in a glass factory", 2),
    ("The child was playing in a park", 0),
    ("The child was picking garbage on the street", 1),
    ("The child was going to school regularly", 0),
    ("The child was working in a hazardous chemical plant", 2),
    ("The child was singing songs at a wedding", 1),
    ("The child was involved in mining activities", 2),
    ("The child was helping in household chores", 0),
    ("The child was taking care of a younger sibling", 0),
    ("The child was sweeping floors in a restaurant", 1),
    ("The child was loading bricks at a construction site", 2),
    ("The child was reading a book at home", 0),
    ("The child was collecting scrap metal for resale", 1),
    ("The child was working in a fireworks factory", 2),
    ("The child was attending an online class", 0),
    ("The child was polishing shoes on the street", 1),
    ("The child was operating heavy machinery", 2),
    ("The child was drawing with crayons", 0),
    ("The child was working as a cleaner in a hotel", 1),
    ("The child was carrying cement bags", 2),
    ("The child was participating in a school sports event", 0),
    ("The child was working as a street performer", 1),
    ("The child was handling toxic waste", 2),
    ("The child was playing video games at home", 0),
    ("The child was washing dishes in a dhaba", 1),
    ("The child was employed in a stone quarry", 2),
    ("The child was learning dance at a studio", 0),
    ("The child was working at a car repair shop", 1),
    ("The child was working in an underground tunnel", 2),
    ("The child was visiting a library", 0),
    ("The child was working in a brick kiln", 2),
    ("The child was taking music lessons", 0),
    ("The child was selling balloons at traffic lights", 1),
    ("The child was making crackers for Diwali", 2),
    ("The child was attending school assembly", 0),
    ("The child was ironing clothes in a laundry shop", 1),
    ("The child was breaking stones with a hammer", 2),
    ("The child was doing painting at home", 0),
    ("The child was delivering groceries on a bicycle", 1),
    ("The child was working in a pesticide plant", 2),
    ("The child was visiting a zoo with family", 0),
    ("The child was serving water in a small eatery", 1),
    ("The child was cleaning drains", 2),
    ("The child was attending a science exhibition", 0),
    ("The child was working as a helper in a meat shop", 1),
    ("The child was engaged in illegal mining", 2),
    ("The child was learning to ride a bicycle", 0),
    ("The child was collecting plastic bottles for sale", 1),
    ("The child was exposed to harmful dust in a factory", 2),
    ("The child was flying a kite", 0),
    ("The child was preparing food in a roadside stall", 1),
    ("The child was welding without protection", 2),
    ("The child was watching cartoons", 0),
    ("The child was cleaning cars on the roadside", 1),
    ("The child was working with molten glass", 2),
    ("The child was attending art class", 0),
    ("The child was pushing carts of goods in a market", 1),
    ("The child was manufacturing firecrackers", 2),
    ("The child was visiting relatives during vacation", 0),
    ("The child was picking cotton in the fields", 1),
    ("The child was lifting iron rods at a workshop", 2),
    ("The child was learning programming on a laptop", 0),
    ("The child was helping in a flower shop", 1),
    ("The child was working under unsafe construction", 2),
    ("The child was singing in a school choir", 0),
    ("The child was packing items in a small warehouse", 1),
    ("The child was handling sharp tools in a factory", 2),
    ("The child was attending a cultural event at school", 0),
    ("The child was vending snacks on a bus", 1),
    ("The child was removing asbestos sheets", 2),
    ("The child was learning chess", 0),
    ("The child was cleaning shop windows", 1),
    ("The child was operating a furnace", 2),
    ("The child was going on a family picnic", 0),
    ("The child was washing clothes at a ghat", 1),
    ("The child was inhaling paint fumes at work", 2),
    ("The child was attending computer class", 0),
    ("The child was serving food in a roadside hotel", 1),
    ("The child was breaking glass for recycling", 2),
    ("The child was doing homework", 0),
    ("The child was collecting rags in a dump yard", 1),
    ("The child was extracting coal manually", 2),
    ("The child was building a LEGO model", 0),
    ("The child was taking care of animals on a farm", 1),
    ("The child was cutting wood with a saw", 2),
    ("The child was gardening in school", 0),
    ("The child was distributing pamphlets", 1),
    ("The child was exposed to open flames at work", 2),
    ("The child was making handmade greeting cards", 0),
    ("The child was working at a sugarcane field", 1),
    ("The child was climbing electric poles for work", 2),
    ("The child was drawing in a notebook", 0),
    ("The child was sweeping temple premises", 1),
    ("The child was melting metals in a furnace", 2),
    ("The child was participating in a quiz contest", 0),
    ("The child was cleaning bus interiors", 1),
    ("The child was working in a leather tanning unit", 2),
    ("The child was visiting a science fair", 0),
    ("The child was polishing metals in a small unit", 1),
    ("The child was handling acids for cleaning", 2),
    ("The child was reading a comic book", 0),
    ("The child was selling newspapers early in the morning", 1),
    ("The child was working in a matchstick factory", 2),
    ("The child was riding a swing in the backyard", 0),
    ("The child was sorting vegetables in a local market", 1),
    ("The child was mixing cement at a construction site", 2),
    ("The child was baking cookies at home", 0),
    ("The child was helping customers in a small shop", 1),
    ("The child was exposed to high temperatures in a furnace", 2),
    ("The child was going to a birthday party", 0),
    ("The child was cleaning tables in a tea stall", 1),
    ("The child was working near open flames", 2),
    ("The child was making a paper craft at home", 0),
    ("The child was shining shoes at the railway platform", 1),
    ("The child was lifting heavy iron sheets", 2),
    ("The child was watching a science video", 0),
    ("The child was collecting firewood for cooking", 1),
    ("The child was working in a battery recycling unit", 2),
    ("The child was swimming at the local pool", 0),
    ("The child was arranging items on store shelves", 1),
    ("The child was working in a toxic paint workshop", 2),
    ("The child was attending a painting competition", 0),
    ("The child was cleaning utensils in a mess", 1),
    ("The child was working with sharp knives in a butcher shop", 2),
    ("The child was helping decorate for a festival", 0),
    ("The child was sewing clothes for sale", 1),
    ("The child was involved in deep-sea fishing", 2),
    ("The child was performing in a school play", 0),
    ("The child was packing grocery bags", 1),
    ("The child was melting plastic waste", 2),
    ("The child was helping water plants", 0),
    ("The child was cutting vegetables in a hotel", 1),
    ("The child was making bricks with bare hands", 2),
    ("The child was doing school homework", 0),
    ("The child was working at a roadside cobbler stall", 1),
    ("The child was spraying pesticide without a mask", 2),
    ("The child was drawing with chalk on the pavement", 0),
    ("The child was delivering milk bottles", 1),
    ("The child was working in a printing press", 2),
    ("The child was playing chess in school", 0),
    ("The child was carrying heavy baskets of fruits", 1),
    ("The child was exposed to asbestos dust", 2),
    ("The child was writing a story", 0),
    ("The child was sweeping stairs in an apartment", 1),
    ("The child was breaking e-waste for metals", 2),
    ("The child was folding clothes at home", 0),
    ("The child was helping arrange chairs at an event", 1),
    ("The child was removing broken glass with bare hands", 2),
    ("The child was going on a school trip", 0),
    ("The child was managing a snack stall", 1),
    ("The child was manufacturing matchboxes", 2),
    ("The child was watching animals at the zoo", 0),
    ("The child was climbing trees to pick fruits for sale", 1),
    ("The child was welding iron rods", 2),
    ("The child was writing an essay", 0),
    ("The child was loading vegetables onto a truck", 1),
    ("The child was exposed to chemical fumes", 2),
    ("The child was feeding pets at home", 0),
    ("The child was acting as a helper in a tea shop", 1),
    ("The child was melting glass using a blowtorch", 2),
    ("The child was creating a scrapbook", 0),
    ("The child was cleaning bicycle chains in a garage", 1),
    ("The child was transporting bricks manually", 2),
    ("The child was reading at the public library", 0),
    ("The child was mopping floors in a hotel", 1),
    ("The child was cooking food in a large vessel", 2),
    ("The child was playing cricket with friends", 0),
    ("The child was sweeping garbage at a market", 1),
    ("The child was mixing dyes in a textile unit", 2),
    ("The child was listening to music", 0),
    ("The child was opening mail in an office", 1),
    ("The child was working near hot machinery", 2),
    ("The child was coloring in a coloring book", 0),
    ("The child was packing sweets at a local shop", 1),
    ("The child was cutting wires for recycling", 2),
    ("The child was attending math tuition", 0),
    ("The child was assisting an electrician", 1),
    ("The child was handling burning coal", 2),
    ("The child was cleaning their school desk", 0),
    ("The child was offering snacks to bus passengers", 1),
    ("The child was dipping hands in dye vats", 2),
    ("The child was visiting a museum with family", 0),
    ("The child was delivering lunch boxes", 1),
    ("The child was crushing stones with a hammer", 2),
    ("The child was going to tuition classes", 0),
    ("The child was collecting empty bottles from trains", 1),
    ("The child was carrying molten metal", 2),
    ("The child was making paper airplanes", 0),
    ("The child was helping in a family-run cafe", 1),
    ("The child was operating cutting machines", 2),
    ("The child was arranging school books", 0),
    ("The child was cleaning walls with detergent", 1),
    ("The child was spraying insecticide on crops", 2),
    ("The child was watering a garden", 0),
    ("The child was polishing brass utensils", 1),
    ("The child was exposed to heavy fumes", 2),
    ("The child was practicing music on a keyboard", 0),
    ("The child was rolling incense sticks", 1),
    ("The child was burning trash near factories", 2),
    ("The child was reading poems aloud", 0),
    ("The child was packing lunch boxes for sale", 1),
    ("The child was breaking large rocks with a hammer", 2),
    ("The child was drawing on a chalkboard", 0),
    ("The child was working at a vegetable stall", 1),
    ("The child was exposed to harmful industrial smoke", 2),
    ("The child was preparing a speech for class", 0),
    ("The child was cleaning tables at a local eatery", 1),
    ("The child was cutting meat in a butcher shop", 2),
    ("The child was playing carrom with friends", 0),
    ("The child was delivering goods on foot", 1),
    ("The child was working barefoot in a furnace", 2),
    ("The child was solving puzzles at home", 0),
    ("The child was folding plastic bags for reuse", 1),
    ("The child was cleaning metal sheets with acid", 2),
    ("The child was drawing on a whiteboard", 0),
    ("The child was guiding customers in a local shop", 1),
    ("The child was cleaning paint containers with chemicals", 2),
    ("The child was visiting a book fair", 0),
    ("The child was washing windows in a hotel", 1),
    ("The child was scraping rust from large pipes", 2),
    ("The child was attending a storytelling session", 0),
    ("The child was rolling chapatis at a stall", 1),
    ("The child was inhaling smoke while cooking on a stove", 2),
    ("The child was working on a science project", 0),
    ("The child was cleaning shoes at a railway station", 1),
    ("The child was transporting coal on a bicycle", 2),
    ("The child was sketching animals for a project", 0),
    ("The child was washing clothes for strangers", 1),
    ("The child was working with hot tandoors", 2),
    ("The child was painting a wall at home", 0),
    ("The child was serving tea in a crowded market", 1),
    ("The child was breaking tiles with a hammer", 2),
    ("The child was making decorations for class", 0),
    ("The child was delivering parcels to nearby shops", 1),
    ("The child was burning wood in a confined space", 2),
    ("The child was packing snacks in paper cones", 1),
    ("The child was assembling electrical plugs", 1),
    ("The child was working with molten metal", 2),
    ("The child was cleaning railway platforms", 1),
    ("The child was repairing punctured tires", 1),
    ("The child was washing greasy parts in a garage", 1),
    ("The child was fixing wires in a ceiling fan", 1),
    ("The child was wrapping sweets for distribution", 1),
    ("The child was making incense cones", 1),
    ("The child was sewing shoes for daily wage", 1),
    ("The child was packing medical syringes in boxes", 1),
    ("The child was selling fish at a local dock", 1),
    ("The child was working at a brick loading zone", 2),
    ("The child was fixing street lamps", 2),
    ("The child was melting aluminum scraps", 2),
    ("The child was polishing boots with strong chemicals", 2),
    ("The child was working with live electric cables", 2),
    ("The child was operating heavy wood-cutting tools", 2),
    ("The child was mixing tar for road construction", 2),
    ("The child was standing near boiling water vats", 2),
    ("The child was digging trenches for drainage", 2),
    ("The child was working in a dye factory", 2),
    ("The child was packing firecrackers without gloves", 2),
    ("The child was exposed to ammonia gas while cleaning", 2),
    ("The child was welding without eye protection", 2),
    ("The child was handling pesticides in a crop field", 2),
    ("The child was collecting coals from railway tracks", 2),
    ("The child was sharpening metal blades", 2),
    ("The child was carrying loads on their head", 2),
    ("The child was bleaching clothes using toxic chemicals", 2),
    ("The child was breaking glass bottles for recycling", 2),
    ("The child was burning tires for scrap metal", 2),
    ("The child was packing cigarettes in small packets", 2),
    ("The child was exposed to carbon monoxide while cooking", 2),
    ("The child was operating a hand-crank sugarcane machine", 2),
    ("The child was dismantling e-waste devices", 2),
    ("The child was making iron rods red-hot", 2),
    ("The child was working in a dark and damp underground tunnel", 2),
    ("The child was inhaling smoke from garbage burning", 2),
    ("The child was tying rebar rods for concrete", 2),
    ("The child was working in a tannery", 2),
    ("The child was crushing stones in a quarry", 2),
    ("The child was carrying hot food containers in bulk", 2),
    ("The child was sharpening knives", 2),
    ("The child was cleaning battery acid from workshop floors", 2),
    ("The child was climbing trees to cut coconuts for sale", 1),
    ("The child was selling fruits from a basket", 1),
    ("The child was carrying water buckets in a wedding hall", 1),
    ("The child was dusting furniture in a guesthouse", 1),
    ("The child was helping lift water cans in a store", 1),
    ("The child was folding paper bags in a packaging shop", 1),
    ("The child was inflating balloons for a fair", 1),
    ("The child was assembling plastic parts", 1),
    ("The child was assisting in a tailor shop", 1),
    ("The child was cutting threads from clothing bundles", 1),
    ("The child was distributing pamphlets", 1),
    ("The child was watching cartoons after school", 0),
    ("The child was assembling a jigsaw puzzle", 0),
    ("The child was participating in a drawing contest", 0),
    ("The child was visiting a temple with family", 0),
    ("The child was helping grandparents in the garden", 0),
    ("The child was attending school classes online", 0),
    ("The child was practicing handwriting", 0),
    ("The child was watching birds on a nature walk", 0),
    ("The child was learning basic coding on a tablet", 0),
    ("The child was painting a pot at school", 0),
    ("The child was planting saplings", 0),
    ("The child was feeding pigeons in the park", 0),
    ("The child was helping organize books on a shelf", 0),
    ("The child was attending a puppet show", 0),
    ("The child was dressing up for a school drama", 0),
    ("The child was baking cupcakes with parents", 0),
    ("The child was decorating the living room for a party", 0),
    ("The child was taking part in a spelling bee", 0),
    ("The child was making a scrapbook for a project", 0),
    ("The child was setting up chairs for a school event", 0),
    ("The child was writing thank-you cards", 0),
    ("The child was helping to clean their own room", 0),
    ("The child was volunteering in a school charity drive", 0),
    ("The child was creating handmade bookmarks", 0),
    ("The child was attending an online quiz", 0),
    ("The child was helping decorate a classroom wall", 0),
    ("The child was learning yoga at home", 0),
    ("The child was reading comics with friends", 0),
    ("The child was helping carry books to the library", 0),
    ("The child was sorting stationery items at home", 0),
    ("The child was folding clothes in their own room", 0),
    ("The child was attending online painting classes", 0),
    ("The child was visiting a science exhibition", 0),
    ("The child was participating in a school quiz", 0),
    ("The child was making crafts for a school project", 0),
    ("The child was attending a cultural dance event", 0),
    ("The child was visiting the zoo with family", 0),
    ("The child was walking the dog in the evening", 0),
    ("The child was playing hide and seek", 0),
    ("The child was watering indoor plants", 0),
    ("The child was making a diorama for class", 0),
    ("The child was organizing toys", 0),
    ("The child was attending an art competition", 0),
    ("The child was singing at a school event", 0),
    ("The child was watching educational videos", 0),
    ("The child was helping clean their own bicycle", 0),
    ("The child was drawing a family portrait", 0),
    ("The child was feeding the pet cat", 0),
    ("The child was building a LEGO structure", 0),
    ("The child was helping decorate a school stall", 0),
    ("The child was helping a sibling with homework", 0),
    ("The child was learning origami", 0),
    ("The child was setting up a bird feeder", 0),
    ("The child was planting flowers with family", 0),
    ("The child was watching a puppet show", 0),
    ("The child was making paper lanterns", 0),
    ("The child was creating greeting cards", 0),
    ("The child was folding origami cranes", 0),
    ("The child was coloring a festival poster", 0),
    ("The child was cleaning up their toys", 0),
    ("The child was attending an online story session", 0),
    
    # MILD CHILD LABOR (1)
    ("The child was working at a fruit juice stall", 1),
    ("The child was delivering newspapers on a bicycle", 1),
    ("The child was sweeping floors in a small shop", 1),
    ("The child was arranging newspapers at a stand", 1),
    ("The child was collecting garbage near a market", 1),
    ("The child was refilling water bottles in a small cafe", 1),
    ("The child was making tea in a roadside stall", 1),
    ("The child was helping stock shelves at a grocery", 1),
    ("The child was serving food in a local eatery", 1),
    ("The child was packing groceries in paper bags", 1),
    ("The child was polishing shoes near a bus stop", 1),
    ("The child was cleaning motorbike parts", 1),
    ("The child was setting up a small street-side stall", 1),
    ("The child was helping manage a stall at a fair", 1),
    ("The child was pushing a cart with vegetables", 1),
    ("The child was slicing bread at a bakery", 1),
    ("The child was arranging chairs at an event", 1),
    ("The child was carrying trays in a roadside cafe", 1),
    ("The child was collecting plastic bottles for resale", 1),
    ("The child was sweeping the floor at a tailoring shop", 1),
    ("The child was organizing bangles in a store", 1),
    ("The child was helping clean dishes at a tea stall", 1),
    ("The child was selling keychains on the street", 1),
    ("The child was organizing change at a cash counter", 1),
    ("The child was delivering snacks to nearby shops", 1),
    ("The child was selling water pouches at a signal", 1),
    ("The child was standing for hours to attract customers", 1),
    ("The child was collecting unused utensils after events", 1),
    ("The child was folding chairs after a local event", 1),
    ("The child was putting up posters on walls", 1),
    
    # SEVERE CHILD LABOR (2)
    ("The child was welding metal pieces without protection", 2),
    ("The child was carrying cement sacks at a site", 2),
    ("The child was exposed to lead while painting", 2),
    ("The child was operating a sugarcane crusher", 2),
    ("The child was working in a firecracker unit", 2),
    ("The child was cleaning sewage pipes", 2),
    ("The child was burning e-waste in the open", 2),
    ("The child was climbing electric poles", 2),
    ("The child was extracting metal using acid baths", 2),
    ("The child was inside a chemical warehouse", 2),
    ("The child was operating a furnace blower", 2),
    ("The child was drilling into stone slabs", 2),
    ("The child was melting tin in open fire", 2),
    ("The child was sharpening knives using machines", 2),
    ("The child was crushing coal with a hammer", 2),
    ("The child was loading metal rods on a truck", 2),
    ("The child was working in a matchbox unit", 2),
    ("The child was bleaching jeans in a denim unit", 2),
    ("The child was working in a carpet factory", 2),
    ("The child was using heavy machinery", 2),
    ("The child was cutting large metal sheets", 2),
    ("The child was dipping cloth in dye tanks", 2),
    ("The child was breathing toxic fumes", 2),
    ("The child was breaking stones under the sun", 2),
    ("The child was working on a scaffold", 2),
    ("The child was exposed to molten plastic", 2),
    ("The child was lifting logs for charcoal", 2),
    ("The child was working without gloves in a dye unit", 2),
    ("The child was filtering waste sludge", 2),
    ("The child was using harmful adhesives", 2),
    
    # Additional MIXED (split into batches of 10 each for balance)
    ("The child was participating in a music rehearsal", 0),
    ("The child was baking with family", 0),
    ("The child was attending a book club", 0),
    ("The child was joining online coding bootcamp", 0),
    ("The child was going on a school picnic", 0),
    ("The child was painting diyas for Diwali", 0),
    ("The child was learning calligraphy", 0),
    ("The child was playing indoor board games", 0),
    ("The child was organizing a bookshelf", 0),
    ("The child was making a scrapbook on nature", 0),
    
    ("The child was helping carry grocery bags for a vendor", 1),
    ("The child was arranging clothes in a garment shop", 1),
    ("The child was delivering snacks to nearby shops", 1),
    ("The child was shining metal utensils in a hotel", 1),
    ("The child was washing scooters in a garage", 1),
    ("The child was helping distribute handbills", 1),
    ("The child was holding a placard for advertisement", 1),
    ("The child was lifting crates of bottled water", 1),
    ("The child was wrapping sweets in wrappers", 1),
    ("The child was assisting a painter with basic tools", 1),
    
    ("The child was handling flammable materials", 2),
    ("The child was melting plastic for molding", 2),
    ("The child was working in a kiln", 2),
    ("The child was loading heavy barrels", 2),
    ("The child was working near high voltage equipment", 2),
    ("The child was cleaning oil-soaked machinery", 2),
    ("The child was lifting bricks at a brick kiln", 2),
    ("The child was cutting wires with pliers", 2),
    ("The child was working in a steel foundry", 2),
    ("The child was sandblasting metal frames", 2)
]

# Basic tokenizer
def tokenize(text):
    return re.findall(r'\b\w+\b', text.lower())

# Build vocabulary
all_tokens = [token for text, _ in data for token in tokenize(text)]
vocab = {"<PAD>": 0, "<UNK>": 1}
vocab.update({word: idx + 2 for idx, word in enumerate(set(all_tokens))})

# Save vocab
with open("model/tokenizer.pkl", "wb") as f:
    pickle.dump(vocab, f)

# Text to tensor
def text_to_tensor(text):
    return torch.tensor([vocab.get(token, vocab["<UNK>"]) for token in tokenize(text)])

# Dataset
class ComplaintDataset(Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        text, label = self.data[idx]
        return text_to_tensor(text), torch.tensor(label)

def collate_batch(batch):
    texts, labels = zip(*batch)
    padded = pad_sequence(texts, batch_first=True, padding_value=vocab["<PAD>"])
    return padded, torch.tensor(labels)

# Model
class LSTMClassifier(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
        super(LSTMClassifier, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim, padding_idx=0)
        self.lstm = nn.LSTM(embedding_dim, hidden_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, output_dim)

    def forward(self, x):
        embedded = self.embedding(x)
        _, (hidden, _) = self.lstm(embedded)
        return self.fc(hidden[-1])

# Params
EMBEDDING_DIM = 64
HIDDEN_DIM = 64
OUTPUT_DIM = 3
BATCH_SIZE = 2
EPOCHS = 10

dataset = ComplaintDataset(data)
dataloader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True, collate_fn=collate_batch)

model = LSTMClassifier(len(vocab), EMBEDDING_DIM, HIDDEN_DIM, OUTPUT_DIM)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Train
for epoch in range(EPOCHS):
    model.train()
    total_loss = 0
    for x_batch, y_batch in dataloader:
        optimizer.zero_grad()
        output = model(x_batch)
        loss = criterion(output, y_batch)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch {epoch+1}/{EPOCHS} - Loss: {total_loss:.4f}")

# Save model
torch.save(model.state_dict(), "model/ml_model.pth")
print("✅ Model trained and saved as model/ml_model.pth")
